# Task 
name: avos_object_detection
data: AVOSObjectDetection
data_config:
  transform: None
  data_dir: /pasteur/data/spatiotemporal-open-surgery/AVOS/data
label_names: ['bovie', 'forceps', 'hand', 'needledriver']
visualize: True