# Task 
name: avos_action_recognition
data: AVOSActionRecognition
data_config:
  transform: None
  data_dir: /path/to/AVOS
label_names: ['cutting', 'tying', 'suturing', 'background']
clip_eval_mode: 'singlelabel'  # single label multi-class classification
shots: zero
