# Task 
name: cholec80_tool_recognition_fewshot
data: Cholec80ToolRecognition
data_config:
  transform: None
  data_dir: /pasteur/data/cholec80
label_names: ['Grasper', 'Bipolar', 'Hook', 'Scissors', 'Clipper', 'Irrigator', 'SpecimenBag']
shots: five
  