# Task 
name: cholec80_tool_recognition
data: Cholec80ToolRecognition
data_config:
  transform: None
  data_dir: /path/to/cholec80
label_names: ['Grasper', 'Bipolar', 'Hook', 'Scissors', 'Clipper', 'Irrigator', 'SpecimenBag']
clip_eval_mode: 'sigmoid'  # multi-label binary classification
shots: zero
