name: cholec80_error_detection
data: ErrorDetection
data_config:
  transform: None
  data_dir: "/pasteur/u/josaklil/data_cache/surgbench_error_det"
  ann_dir: "/pasteur/data/soar_wellcome_save/id2chosen_csv_errors_v2"
  dataset_name: "Cholec80"
label_names: []
clip_eval_mode: 'singlelabel'  # mean IoU
shots: zero