# Task 
name: heichole_error_detection
data: ErrorDetection
data_config:
  transform: None
  data_dir: /path/to/data
  ann_dir: /path/to/annotations
  dataset_name: "Heichole"
label_names: []
shots: zero