# Task 
name: heichole_error_classification
data: ErrorClassification
data_config:
  transform: None
  data_dir: "/pasteur/u/josaklil/data_cache/surgbench_error_clf"
  ann_dir: "/pasteur/data/soar_wellcome_save/"
  dataset_name: "Heichole"
label_names: ['Bleeding', 'Bile Spillage', 'Thermal Injury', 'Perforation']
clip_eval_mode: 'singlelabel'  # single label multi-class classification
shots: zero