# Task 
name: heichole_tool_recognition_fewshot
data: HeiCholeDataloader
data_config:
  transform: None
  data_dir: /path/to/heichole
label_names: ['Grasper', 'Clipper', 'Coagulation instruments', 'Scissors', 'Suction-irrigation', 'Specimen bag', 'Stapler']
clip_eval_mode: 'sigmoid'  # multi-label binary classification
shots: one
